In [1]:
import pandas as pd

In [96]:
temp = pd.read_excel('raw_data/SuEatableLife_Food_Fooprint_database.xlsx', sheet_name=1, header=0)
suffer = pd.read_excel('raw_data/SuEatableLife_Food_Fooprint_database.xlsx', sheet_name=6, header=0)

In [97]:
temp['FOOD COMMODITY GROUP'].unique()
temp.head

<bound method NDFrame.head of        FOOD COMMODITY GROUP                  Food commodity ITEM  \
0    AGRICULTURAL PROCESSED                          BEER IN CAN
1    AGRICULTURAL PROCESSED                        BEER IN GLASS
2    AGRICULTURAL PROCESSED                     BEER MODULAR CAN
3    AGRICULTURAL PROCESSED  CHOCOLATE OR CREAM FILLED COOKIES**
4    AGRICULTURAL PROCESSED                     SIMPLE COOKIES**
..                      ...                                  ...
319                 FISHING                              OCTOPUS
320                 FISHING                                SQUID
321                 FISHING                       PRAWNS/SHRIMPS
322                 FISHING                          OCTOPUS (F)
323                 FISHING                   PRAWNS/SHRIMPS (F)

     Carbon Footprint kg CO2eq/kg or l of food ITEM  \
0                                          0.693000
1                                          0.960500
2                                          0.530600
3                                          1.533000
4                                          1.390750
..                                              ...
319                                        5.800000
320                                        6.910000
321                                        7.040000
322                                        7.878611
323                                       15.065000

    Uncertainty    low (L) high (H)          Suggested CF value  \
0                                 L                     OK item
1                                 L                     OK item
2                                 L                     OK item
3                                 L                     OK item
4                                 L                     OK item
..                              ...                         ...
319                               H  better typol. or subtypol.
320                               H  better typol. or subtypol.
321                               L                     OK item
322                               H             better typology
323                               L                     OK item

    Food commodity TYPOLOGY  Carbon Footprint g CO2eq/g o cc of food TYPOLOGY  \
0                      BEER                                              0.69
1                      BEER                                              0.69
2                      BEER                                              0.69
3                  BISCUITS                                              1.47
4                  BISCUITS                                              1.47
..                      ...                                               ...
319               SHELLFISH                                              5.67
320               SHELLFISH                                              5.67
321               SHELLFISH                                              5.67
322        SHELLFISH FROZEN                                             11.47
323        SHELLFISH FROZEN                                             11.47

                Food commodity sub-TYPOLOGY  \
0                                         -
1                                         -
2                                         -
3                                         -
4                                         -
..                                      ...
319                    CEPHALOPOD (SUB-TYP)
320                    CEPHALOPOD (SUB-TYP)
321  CRUSTACEAN* (SUB-TYP) (Prawns/Shrimps)
322                                       -
323                                       -

    Carbon Footprint g CO2eq/g o cc of food sub-TYPOLOGY
0                                                    -
1                                                    -
2                                                    -
3                                                    -
4                                                    -
..                                                 ...
319                                                5.8
320                                                5.8
321                                               7.04
322                                                  -
323                                                  -

[324 rows x 9 columns]>

In [103]:
pain = temp.loc[temp['FOOD COMMODITY GROUP'] == 'FISHING']



temp.sort_values(by= 'Carbon Footprint kg CO2eq/kg or l of food ITEM',ascending=False).head(50).iloc[:,0:3]
temp.loc[temp['Food commodity ITEM'] == 'APPLE']

,FOOD COMMODITY GROUP,Food commodity ITEM,Carbon Footprint kg CO2eq/kg or l of food ITEM,Uncertainty low (L) high (H),Suggested CF value,Food commodity TYPOLOGY,Carbon Footprint g CO2eq/g o cc of food TYPOLOGY,Food commodity sub-TYPOLOGY,Carbon Footprint g CO2eq/g o cc of food sub-TYPOLOGY
167,CROPS,APPLE,0.2539,L,OK item,FRUIT OPENFIELD,0.4,FRUIT OTHER,0.32

In [101]:
suffer.sort_values(by= 'Water Footprint liters water/kg o liter of food ITEM',ascending=False).head(20).iloc[:,0:3]

,FOOD COMMODITY GROUP,Food commodity ITEM,Water Footprint liters water/kg o liter of food ITEM
273,CROPS,SAFFRON,731000.0
291,CROPS,VANILLA BEAN,126505.0
198,CROPS,CLOVE,61205.0
95,ANIMAL HUSBANDRY,ASS MEAT,50274.0
141,ANIMAL HUSBANDRY,MULE MEAT,50274.0
130,ANIMAL HUSBANDRY,HORSE MEAT,50274.0
128,ANIMAL HUSBANDRY,HINNY MEAT,50274.0
233,CROPS,MACE,34319.0
244,CROPS,NUTMEG,34319.0
186,CROPS,CARDAMOM,34319.0
15,AGRICULTURAL PROCESSED,COCOA BUTTER,33938.0
17,AGRICULTURAL PROCESSED,COCOA PASTE,24238.0
99,ANIMAL HUSBANDRY,BEEF CURED MEAT,23799.0
226,CROPS,KOLA NUT,23391.0
67,AGRICULTURAL PROCESSED,SESAM OIL,21793.0
20,AGRICULTURAL PROCESSED,COFFEE ROASTED,19956.0
201,CROPS,COFFEE BEAN,19928.0
13,AGRICULTURAL PROCESSED,CHOCOLATE,17196.0
224,CROPS,HOP EXTRACT,16259.0
162,CROPS,ALMOND SHELLED,16095.0